### PR TITLE
Upgrade to Plone 5

### PR DESCRIPTION
**Pull request by busykoala**
🚧 DO NOT MERGE - https://github.com/4teamwork/ftw.book/pull/111 is going to handle this pull. 🚧 

Close https://github.com/4teamwork/izug.organisation/issues/1514

### CODE REVIEW

**Comment by busykoala** [comment]
I think it's not worthwhile trying to rebase the commits into a nice history, so going through the commit history for the review does not seem to make sense.

**Comment by jone** [comment]
@busykoala could you update this pull request onto the state of the current `master`?
Either rebase onto `master` or merge `master` into `plone5`.
And please also change the merge base of the pull request afterwards.

**Comment by jone** [comment]
@busykoala do we still need this one? We have #111  now 🤔

**Comment by busykoala** [comment]
I'd like to keep it until I know better how the merge on the other branch went.

**Comment by busykoala** [comment]
Close in favour of https://github.com/4teamwork/ftw.book/pull/112

**Pull request closed without merging**
